chore(setup): Containerize repository
algolia/algoliasearch-django pull request #310
Opened 2021-03-05 13:40 UTC by tkrugg

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no   
| BC breaks?        | no     
| Related Issue     | Fix  #302
| Need Doc update   | no

## Describe your change

This commit adds:
- Dockerfile
- Specific instructions for setting up adn running the tests with Docker
- Adds link to DOCKER_README.md in main README.md

## What problem is this fixing?

#302

2021-03-05 14:41 UTC, chloelbn requested changes

2021-03-05 14:41 UTC, chloelbn commented on DOCKER_README.md
> +docker run -it --rm --env ALGOLIA_APP_ID --env ALGOLIA_API_KEY -v $PWD:/code -w /code algolia-scout-extended bash
```suggestion
docker run -it --rm --env ALGOLIA_APPLICATION_ID --env ALGOLIA_API_KEY -v $PWD:/code -w /code algoliasearch-django bash
```

2021-03-05 14:41 UTC, chloelbn commented on DOCKER_README.md
> +export ALGOLIA_APP_ID=XXXXXX
```suggestion
export ALGOLIA_APPLICATION_ID=XXXXXX 
```

2021-03-05 14:41 UTC, chloelbn commented on DOCKER_README.md
> +export ALGOLIA_SEARCH_API_KEY=XXXX
is it necessary?

2021-03-05 14:41 UTC, chloelbn commented on DOCKER_README.md
> +docker run -it --rm --env ALGOLIA_APP_ID=XXXXXX \
```suggestion
docker run -it --rm --env ALGOLIA_APPLICATION_ID=XXXXXX \
```

2021-03-05 15:11 UTC, tkrugg commented on DOCKER_README.md
> +export ALGOLIA_SEARCH_API_KEY=XXXX
```suggestion
```

2021-03-08 15:17 UTC, chloelbn commented
Most of the tests pass but I still get this error in the second part
```
ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'management'
```

2021-03-09 09:41 UTC, tkrugg commented
> Most of the tests pass but I still get this error in the second part
> 
> ```
> ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'management'
> ```
Hi  @chloelbn I'm not sure how you got the error. Could you explicit the steps to reproducing the issue?

2021-03-10 11:09 UTC, chloelbn approved these changes

2021-03-12 13:58 UTC, merged